#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';

# https://metacpan.org/pod/JSON
use JSON qw( decode_json );

my $name;

if ($ENV{'REQUEST'}) {
  my $request = decode_json($ENV{'REQUEST'});
  $name = $request->{'params'}{'name'};
}

if (!$name) {
  $name = "World";
}

print "Hello, $name!\nThis is Perl!\n";
